### PR TITLE
Adding setup deatils for PyPI

### PR DESCRIPTION
**Pull request by wangzhizhou**
If you have and PyPI Account, let me know, I can delete the package I have published. And you can use your account to publish it. as this pr show

### CODE REVIEW

**Comment by conqp** [comment]
Hi @wangzhizhou 

Thanks for the feedback.
My PyPI account has the same name as mine here.
I will review your pull request today and then merge it.

**Comment by conqp** [comment]
Sorry, I screwed up the edit of your pull request.
I added the necessary changes for publishing it on PyPI to setup.conf in 4c78ae2168ae53b13fc20e9b01f3b65dd6cac73d.

**Comment by wangzhizhou** [comment]
I have delete the package of my account on PyPI, so you can publish with the same name

**Comment by conqp** [comment]
Thanks. I just uploaded it: https://pypi.org/project/mcipc/

**Pull request closed without merging**
