### PR TITLE
fix for #20

### PR DESCRIPTION
**Pull request by gilesknap**
This looks to be as I originally expected now.

This code
```
from mcipc.rcon import FillMode
from mcipc.rcon.builder import Item, Vec3, Direction, mktunnel, Profile
from mcipc.rcon.builder.types import Anchor
from mcipc.rcon.je import Client


def knot(client: Client, mid: Vec3, a: Anchor):
    p: Profile = [
        [Item.RED_CONCRETE, Item.AIR, Item.GREEN_CONCRETE],
        [Item.AIR, Item.AIR, Item.AIR],
        [Item.BLUE_CONCRETE, Item.AIR, Item.YELLOW_CONCRETE],
    ]
    mktunnel(client, p, mid, direction=Direction.NORTH, length=5, mode=FillMode.KEEP, anchor=a)
    mktunnel(client, p, mid, direction=Direction.SOUTH, length=5, mode=FillMode.KEEP, anchor=a)
    mktunnel(client, p, mid, direction=Direction.EAST, length=5, mode=FillMode.KEEP, anchor=a)
    mktunnel(client, p, mid, direction=Direction.WEST, length=5, mode=FillMode.KEEP, anchor=a)
    mktunnel(client, p, mid, direction=Direction.UP, length=5, mode=FillMode.KEEP, anchor=a)
    # mktunnel(client, p, mid, direction=Direction.DOWN, length=5, mode=FillMode.KEEP, anchor=a)


with Client("localhost", 25901, passwd="spider") as client:
    # clear 150 * 150 * 100 centred on world_middle
    clear: Profile = [[Item.AIR] * 150] * 150
    mktunnel(client, clear, Vec3(75, 5, -75), direction=Direction.UP, length=200)

    mid = Vec3(0, 50, 0)
    knot(client, mid, Anchor.TOP_LEFT)  # all should join at RED
    mid = Vec3(10, 50, 0)
    knot(client, mid, Anchor.TOP_RIGHT)  # all shouls join at GREEN
    mid = Vec3(20, 50, 0)
    knot(client, mid, Anchor.BOTTOM_LEFT)  # joins at BLUE
    mid = Vec3(30, 50, 0)
    knot(client, mid, Anchor.BOTTOM_RIGHT)  # joins at YELLOW

```

Produces these shapes:
image

### CODE REVIEW

**Comment by gilesknap** [comment]
I have also added the MIDDLE anchor. Which makes the shape on the right when knot() is called:
image

**Comment by conqp** [comment]
@gilesknap Thanks for the patches. I will review them over the week.

Currently I am considering to outsource the builder subsystem into an own project due to its complexity and topical difference to the core of *mcipc*. While I would like to continue tinkering with world builder features, mcipc was originally intended to provide an interface to communicate with Minecraft servers. So the builder subsystem is actually a good showcase for how mcipc can be used, but probably shouldn't be part of it.
The benefit of outsourcing it into a separate project would also make it sensible to use *numpy* and/or *pandas* for vector and matrix calculations, instead of doing it by hand.

**Comment by gilesknap** [comment]
@conqp I was thinking the same thing when tinkering with builder. mktunnel would benefit from numpy probably (I spent ages fiddling with beer mats to come up with this patch).

I'm  beginning to pull together a set  of classes for assisting with not only building but also with creating interactive code. So I would likely have some contributions to a separate builder project. For example here is a draft of some code to create buttons and levers that call python functions on state change: https://github.com/gilesknap/mc-rcon-test/blob/main/button.py

**Comment by conqp** [comment]
@gilesknap Thank you for your effort on helping to improve *mcipc*. However, this pull request is getting kind of huge. The latest fix for the missing return of the command proxy for example has nothing to do with the rest of the builder subsystem. Please create separate pull issues and / or requests for unrelated bugs or improvements in the future. Thank you for your understanding.

**Review by conqp — COMMENTED** [review]
This would duplicate the functionality provided by `mcipc.rcon.functions.stringify()`.
If you pass a `Vec3` to a `mcipc.rcon.client.Client` instances `run()`, it will automatically be serialized using aforementioned `stringify()`.

**Comment by conqp** [comment]
Outsourced builder subsystem to: https://github.com/conqp/mcwb

**Comment by gilesknap** [comment]
> @gilesknap Thank you for your effort on helping to improve _mcipc_. However, this pull request is getting kind of huge. The latest fix for the missing return of the command proxy for example has nothing to do with the rest of the builder subsystem. Please create separate issues and / or pull requests for unrelated bugs or improvements in the future. Thank you for your understanding.

oops - I should not have been working in master - apologies.



> This would duplicate the functionality provided by `mcipc.rcon.functions.stringify()`.
> If you pass a `Vec3` to a `mcipc.rcon.client.Client` instances `run()`, it will automatically be serialized using aforementioned `stringify()`.

This did not seem to work for me (I got 'Vec3(x=....' (It was in the execute.run) - I'll investigate further.

**Pull request closed without merging**
